export const MISSION_CONTROL_VERSION='TCX_MISSION_CONTROL_V1';
const esc=x=>String(x??'—').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
export function missionControlSnapshot({health,portfolio,discovery,storage}={}){
 return {version:MISSION_CONTROL_VERSION,generatedAt:Date.now(),health:health||{},portfolio:portfolio||{},discovery:discovery||{},storage:storage||{},execution:'SHADOW_ONLY',canExecuteLive:false};
}
export function renderMissionControlHtml(s={}){
 const j=JSON.stringify(s).replace(/</g,'\\u003c');
 return `<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>TCX Mission Control</title><style>
*{box-sizing:border-box}body{margin:0;background:#090b10;color:#edf1f7;font-family:ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}main{max-width:1180px;margin:auto;padding:18px}.top{display:flex;justify-content:space-between;gap:12px;align-items:center}.muted{color:#8993a5}.badge{border:1px solid #2a3140;border-radius:999px;padding:6px 10px;font-size:12px}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:16px 0}.card{background:#11151d;border:1px solid #232a38;border-radius:14px;padding:14px}.big{font-size:24px;font-weight:750;margin-top:5px}.ok{color:#8ee6a7}.warn{color:#ffd27a}.bad{color:#ff8b8b}.section{margin-top:18px}.section h2{font-size:14px;letter-spacing:.08em;color:#aeb7c6}.row{display:flex;justify-content:space-between;gap:12px;border-top:1px solid #202633;padding:9px 0;font-size:13px}.row:first-child{border-top:0}.bar{height:6px;background:#202633;border-radius:9px;overflow:hidden;margin-top:7px}.fill{height:100%;background:#d8dee9}.foot{margin:24px 0;color:#747f91;font-size:12px}@media(max-width:760px){.grid{grid-template-columns:repeat(2,1fr)}main{padding:12px}.top{align-items:flex-start;flex-direction:column}}
</style></head><body><main><div class="top"><div><div class="muted">TCX</div><h1>Mission Control</h1></div><div class="badge">SHADOW_ONLY · REAL ORDERS BLOCKED</div></div>
<div id="app"></div><div class="foot">Read-only observability surface. Auto refresh 10s. Readiness and research scores are not trading permission.</div></main>
<script>let S=${j};const E=x=>String(x??'—').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));const state=x=>String(x||'UNKNOWN');const cls=x=>/READY|HEALTHY|NORMAL|PASS|ONLINE|true/i.test(String(x))?'ok':/ERROR|BLOCK|false|UNHEALTHY/i.test(String(x))?'bad':'warn';
function render(){const h=S.health||{},p=S.portfolio||{},d=S.discovery||{},st=S.storage||{},research=p.researchActivity||{},coverage=h.researchCoverage||{};const op=h.operationalReadiness||{},oms=h.shadowOms||{},f=h.institutionalForecastRuntime||{},tg=h.telegramPolling||{},lr=h.biggjLivingResearch||{},skill=lr.skillTree||{},protocols=lr.researchProtocols||{},reviews=lr.researchReviews||{};const cards=[['Runtime',op.ready?'READY':'CHECK',op.ready?'ok':'warn'],['Primary open',p.openPositions??0,''],['Primary closed',p.closedTrades??0,''],['Research open',research.openPositions??0,''],['Research required',lr.researchRequired??0,Number(lr.researchRequired||0)>0?'warn':''],['Research skills',lr.discoveredResearchOnlySkills??0,Number(lr.discoveredResearchOnlySkills||0)>0?'warn':''],['Coverage',Number.isFinite(Number(coverage.averageCoverage))?Math.round(Number(coverage.averageCoverage)*100)+'%':'—',Number(coverage.blocked||0)>0?'warn':''],['Equity',Number(p.equityQuote||0).toFixed(2)+' USDT','']];
let html='<div class="grid">'+cards.map(x=>'<div class="card"><div class="muted">'+E(x[0])+'</div><div class="big '+x[2]+'">'+E(x[1])+'</div></div>').join('')+'</div>';
const rows=[['Operational readiness',op.ready?'READY':op.status||'CHECK'],['Audit ledger',h.institutionalKernel?.ledgerHealthy],['Market fabric',h.marketDataFabric?.healthy],['Forecast runtime',f.healthy??f.status],['Living research',lr.healthy===false?'DEGRADED':lr.integrity||'UNKNOWN'],['Living agenda / required',(lr.activeAgendaItems??0)+' / '+(lr.researchRequired??0)],['Shadow OMS',oms.healthy],['OMS active / filled',(oms.active??0)+' / '+(oms.filled??0)],['Coverage healthy / blocked',(coverage.healthy??0)+' / '+(coverage.blocked??0)],['Top research blocker',coverage.topBlockedSources?.[0]?.id||'none'],['Worst coverage',coverage.worstSymbols?.[0]?coverage.worstSymbols[0].symbol+' · '+Math.round(Number(coverage.worstSymbols[0].coverage||0)*100)+'%':'none'],['Telegram last poll',tg.lastPollAt?new Date(tg.lastPollAt).toLocaleTimeString():'—'],['Telegram error',tg.lastPollError||'none'],['Trade scan coins',d.checkedCoins??0],['Normal / exploration trades',(d.standardTrades??0)+' / '+(d.explorationTrades??0)],['Calibrated horizons',(d.totalCalibratedHorizons??0)+' / '+(d.totalHorizons??0)],['Top trade blocker',d.topBlockers?.[0]?.text||'none']];
html+='<div class="card section"><h2>SYSTEM STATUS</h2>'+rows.map(x=>'<div class="row"><span>'+E(x[0])+'</span><strong class="'+cls(x[1])+'">'+E(x[1])+'</strong></div>').join('')+'</div>';
const livingAgenda=lr.topResearchBottlenecks||lr.topAgenda||[];const skillCounts=skill.counts||{};html+='<div class="card section"><h2>LIVING RESEARCH</h2>'+(livingAgenda.length?livingAgenda.map(x=>'<div class="row"><span>'+E(x.assumptionId)+' · '+E(x.primaryCapabilityId)+'</span><strong class="'+cls(x.status)+'">'+E(x.status)+' · IV '+E(x.informationValue)+'</strong></div>').join(''):'<div class="muted">No active persistent thesis bottlenecks</div>')+'<div class="row"><span>Research-only skills</span><strong>'+E((lr.discoveredResearchOnlySkillIds||[]).join(', ')||lr.discoveredResearchOnlySkills||0)+'</strong></div><div class="row"><span>Skill tree</span><strong>'+E((skill.nodeCount??0)+' nodes · '+(skill.discovered??0)+' discovered · '+(skill.trusted??0)+' trusted')+'</strong></div><div class="row"><span>Protocols / reviews</span><strong>'+E((protocols.total??0)+' / '+(reviews.open??0))+'</strong></div><div class="row"><span>Execution authority</span><strong class="ok">NONE · SHADOW_ONLY · ABSTAIN</strong></div></div>';
const pos=p.positions||[];html+='<div class="card section"><h2>OPEN SHADOW POSITIONS</h2>'+(pos.length?pos.slice(0,12).map(x=>'<div class="row"><span>'+E(x.symbol)+' · '+E(x.side)+' · '+E(x.entryMode||'STANDARD')+'</span><strong>'+E(x.lastMark?.unrealizedNetPnlQuote??x.unrealizedPnlQuote??x.pnlQuote??'—')+'</strong></div>').join(''):'<div class="muted">No open shadow positions</div>')+'</div>';
document.getElementById('app').innerHTML=html}render();setInterval(async()=>{try{const r=await fetch('/mission-control.json',{cache:'no-store'});if(r.ok){S=await r.json();render()}}catch{}},10000);</script></body></html>`;
}
